using System;

public class ControlTable
{
    public int MAIN_KEY { get; set; }
    public int CASHIER { get; set; }
    public string NAME { get; set; }
    public string ADDRESS { get; set; }
    public string PHONE { get; set; }
    public string FAX { get; set; }
    public int DEPART { get; set; }
    public short SALESPERSON { get; set; }
    public int MAX_DISCOUNT { get; set; }
    public int DISCOUNT_TYPE { get; set; }
    public float VAT_PERCENT { get; set; }
    public DateTime VAT_LAST_DATE { get; set; }
    public float VAT_OLD_PERCENT { get; set; }
    public int MAX_CHANGE { get; set; }
    public short MIN_CREDIT_NOTE { get; set; }
    public short DROWER { get; set; }
    public string ROUND { get; set; }
    public string REMARK1 { get; set; }
    public string REMARK2 { get; set; }
    public string SHAV_TIME { get; set; }
    public string PASWORD { get; set; }
    public float OBLIGO { get; set; }
    public short PRINTER_TYPE1 { get; set; }
    public short BARCODE_TYPE { get; set; }
    public short INVOICE_STYLE { get; set; }
    public short ACC_COPY { get; set; }
    public short INV_COPY { get; set; }
    public short SELF_COPY { get; set; }
    public short DEAL_COPY { get; set; }
    public short ENT_COPY { get; set; }
    public short TRN_COPY { get; set; }
    public short PIK_COPY { get; set; }
    public short CUR_COPY { get; set; }
    public short CRT_COPY { get; set; }
    public short COU_COPY { get; set; }
    public short IVC_COPY { get; set; }
    public short ORD_COPY { get; set; }
    public short SOD_COPY { get; set; }
    public string HOV { get; set; }
    public int PIZA_TOSEFET { get; set; }
    public short ACCLPT { get; set; }
    public short INVLPT { get; set; }
    public short SELFLPT { get; set; }
    public short DEALLPT { get; set; }
    public short ENTLPT { get; set; }
    public short SEGLPT { get; set; }
    public short ORDLPT { get; set; }
    public short PIKLPT { get; set; }
    public short TRNLPT { get; set; }
    public short COULPT { get; set; }
    public short PACLPT { get; set; }
    public short RECLPT { get; set; }
    public short PROLPT { get; set; }
    public short CURLPT { get; set; }
    public short CRTLPT { get; set; }
    public short IVCLPT { get; set; }
    public short SODLPT { get; set; }
    public DateTime LAST_CALL_DATE { get; set; }
    public int LAST_ACCOUNT { get; set; }
    public int LAST_INVOICE { get; set; }
    public int LAST_SELF_INVOICE { get; set; }
    public int LAST_DEAL_INVOICE { get; set; }
    public int LAST_PIKADON { get; set; }
    public int LAST_DEPOIT { get; set; }
    public int LAST_TRANSFER { get; set; }
    public int LAST_TRN_DELETE { get; set; }
    public int LAST_PACKING { get; set; }
    public int LAST_PROFORMA { get; set; }
    public int LAST_ORDER { get; set; }
    public int LAST_COUNT { get; set; }
    public int LAST_ENTRY { get; set; }
    public int LAST_FIX { get; set; }
    public int LAST_CHECK { get; set; }
    public int LAST_SUPLIERFOLIOW { get; set; }
    public int LAST_LOST { get; set; }
    public int LAST_Z { get; set; }
    public int LAST_X { get; set; }
    public int LAST_CLUB { get; set; }
    public int LAST_CUSTOMER { get; set; }
    public int LAST_CUR { get; set; }
    public int LAST_CUR_P { get; set; }
    public int LAST_CRT { get; set; }
    public int LAST_IVC_HEAD { get; set; }
    public int LAST_SOD_HEAD { get; set; }
    public string IF_DEPOSIT { get; set; }
    public string IF_INVENTORY { get; set; }
    public string IF_LINE_TOTAL { get; set; }
    public string IF_LINE_DISCOUNT { get; set; }
    public string IF_GIFTS { get; set; }
    public string IF_NET { get; set; }
    public string IF_CHANGE_PRICE { get; set; }
    public string IF_HEADER { get; set; }
    public string IF_UPERCASE { get; set; }
    public string IF_CHECK_CHECK { get; set; }
    public string IF_TRNCARD { get; set; }
    public string IF_TRNDATE { get; set; }
    public string IF_PERUTCHECKS { get; set; }
    public string IF_PASWORD { get; set; }
    public string IF_PRINT_LAST_DEBTS { get; set; }
    public string IF_PIZERIA { get; set; }
    public string IF_SLIP { get; set; }
    public string IF_PRINTDOS { get; set; }
    public string IF_TSTART { get; set; }
    public string IF_ITONIT_CUSTOMER { get; set; }
    public string IF_ITEM_DESCRIPTION_ENG { get; set; }
    public string IF_RACT_NAME_ENGLISH { get; set; }
    public string IF_REMARK_ACC_HEAD { get; set; }
    public string IF_PRINT_AROMA { get; set; }
    public string IF_SHIPPING { get; set; }
    public string IF_OPEN_ITEM { get; set; }
    public string IF_LOGO { get; set; }
    public string IF_CASHMINUS { get; set; }
    public string IF_IT_DESC2 { get; set; }
    public string IF_COLUMM_DISCOUNT { get; set; }
    public string IF_BUTTONS { get; set; }
    public string IF_8_PRINTING { get; set; }
    public string IF_CR_NOTE { get; set; }
    public string IF_HAKAFA { get; set; }
    public string IF_TRN_OLD { get; set; }
    public string IF_TOW_COMPANIES { get; set; }
    public string IF_TOTAL_DISCOUNT { get; set; }
    public string IF_MENU { get; set; }
    public string IF_NO_PRINTER { get; set; }
    public string TRANSFER_VAT { get; set; }
    public string INV_VAT { get; set; }
    public string HAKAFATOBANKTRANSFER { get; set; }
    public string DONOTPRINTPHONECREDITVOUC { get; set; }
    public string ALLIAS { get; set; }
    public short COMP_TYPE { get; set; }
    public short SHOP_TYPE { get; set; }
    public int CLDEFAULT { get; set; }
    public string CR_DISK { get; set; }
    public int ID { get; set; }
    public string ST_REM1 { get; set; }
    public string ST_REM2 { get; set; }
    public string ST_REM3 { get; set; }
    public short ORD_NAME { get; set; }
    public string IF_HEADOFFICE { get; set; }
    public int QTY3DIGIT { get; set; }
    public int ACC_ITEM_FONT_SIZE { get; set; }
    public short CLUBRENEWYEARS { get; set; }
    public float SHIPPING { get; set; }
    public string LOGOREMARK1 { get; set; }
    public string LOGOREMARK2 { get; set; }
    public short LOGOHEADERLINES { get; set; }
    public short LOGOFOOTERLINES { get; set; }
    public string HHHDIR { get; set; }
    public float CLACC { get; set; }
    public float SALACC { get; set; }
    public float VATACC { get; set; }
    public float SALNOVAT { get; set; }
    public string CID { get; set; }
    public string CASHMINUS { get; set; }
    public string SALEREPORTEOD { get; set; }
    public string IBMMACHINE { get; set; }
    public string HHHSPLITSAL { get; set; }
    public string ADDWRHCODE { get; set; }
    public string BONUS { get; set; }
    public string NAMEOFMIDA { get; set; }
    public short LOCATIONOFCOLOR { get; set; }
    public short LOCATIONOFMIDA { get; set; }
    public short LENGTHOFMIDA { get; set; }
    public short LOCATIONOFSMELL { get; set; }
    public short LENGTHOFSMELL { get; set; }
    public short LOCATIONOFID { get; set; }
    public string CURR_REMARKS { get; set; }  // BLOB SUB_TYPE TEXT SEGMENT SIZE 80,
    public string ITEMSLOCATION { get; set; }
    public string SCALE_TYPE { get; set; }
    public short SCALECOM { get; set; }
    public string MAINCOMPUTER { get; set; }
    public short LONDRYDAYS { get; set; }
    public short LONDRYTIME { get; set; }
    public string SECONDCOMPANYALLIAS { get; set; }
    public string SECONDCOMPANYACCTION { get; set; }
    public short COSTDEFAULT { get; set; }
    public DateTime EDT { get; set; }
    public short EDD { get; set; }
    public string IF_LOAD_ITEM { get; set; }
    public short LOS_COPY { get; set; }
    public short LOSLPT { get; set; }
    public int LAST_LOS_HEAD { get; set; }
    public short SCREENRESULOTION { get; set; }
    public short MODEMLOCATION { get; set; }
    public string STIKERLABEL { get; set; }
    public short SEG_COPY { get; set; }
    public string SECONDPRINTER { get; set; }
    public string BSD { get; set; }
    public short PRINTERSNUMBER { get; set; }
    public string THIRDPRINTER { get; set; }
    public string FORTHPRINTER { get; set; }
    public string BARPRINTERSUMPRINT { get; set; }
    public short PAC_PRICE { get; set; }
    public string NOF8 { get; set; }
    public string IF_CHAIRSNAME { get; set; }
    public string IF_WAITERS { get; set; }
    public string SMSACCOUNT { get; set; }
    public string SMSPASWORD { get; set; }
    public string SMSPNUMBER { get; set; }
    public string SALECEAPFROMTHREE { get; set; }
    public short MAINPRINTERCOMM { get; set; }
    public string NOSCALE { get; set; }
    public float OPENDAYAMMOUNT { get; set; }
    public string NOF4_F5 { get; set; }
    public int LAST_STATMENT { get; set; }
    public string IF_STATMENT { get; set; }
    public short STMLPT { get; set; }
    public string TREETOINV { get; set; }
    public string AUTOCREATEITEM { get; set; }
    public string IF_ERN { get; set; }
    public short MODEMCOM { get; set; }
    public string ERNADSL { get; set; }
    public string ERNOUT03 { get; set; }
    public string ERNMERCAZIA { get; set; }
    public string SHVADOS { get; set; }
    public string IF_PIKADON { get; set; }
    public string IF_COMMMAINCOMPUTER { get; set; }
    public string DRIVEMAINCOMPUTER { get; set; }
    public string EMAIL { get; set; }
    public string IP { get; set; }
    public string COUNTEOD { get; set; }
    public float MAXCHANGEPRC { get; set; }
    public string ACC_ITEMFIX { get; set; }
    public string NOHAKAFANOTE { get; set; }
    public string SHORTINV { get; set; }
    public string EODDEBTS { get; set; }
    public string IFPROFITDISCOUNT { get; set; }
    public string ITEMSFINDDESC { get; set; }
    public string LOCALNET { get; set; }
    public string NIKUI_BMAKOR { get; set; }
    public string TOPUPIP { get; set; }
    public string TOPUPLOGINNAME { get; set; }
    public string TOPUPPASSWORD { get; set; }
    public string TOPUPHEX { get; set; }
    public string TOPUPTERMINAL { get; set; }
    public short BANKDEFAULT { get; set; }
    public string ACCPASWORD { get; set; }
    public string CHANGEPRINTER { get; set; }
    public string NOPIKADON { get; set; }
    public string SALEITDISCOUNT { get; set; }
    public string SALEQTYAMT { get; set; }
    public string INV2KIBUTZ { get; set; }
    public int KIBUTTZACC { get; set; }
    public string DRAWER { get; set; }
    public string PRICE3TOSTIKER { get; set; }
    public string SALEAMT { get; set; }
    public string SUPBARCODE { get; set; }
    public float HAGDALAAMT { get; set; }
    public short Z_COPY { get; set; }
    public short FIXLPT { get; set; }
    public short FIX_COPY { get; set; }
    public short SHPLPT { get; set; }
    public short SHP_COPY { get; set; }
    public int LAST_SHP { get; set; }
    public string ST_REM4 { get; set; }
    public short OUTSOFTWARE { get; set; }
}

public class ItemsTable
{
    public string IT_CODE { get; set; }  
    public string IT_DESC { get; set; }
    public string BARCODE { get; set; }
    public string IT_S_CODE { get; set; }
    public string ALTKEY { get; set; }
    public float RUNKEY { get; set; }
    public int ITSORT { get; set; }
    public int CUT { get; set; }
    public int ROLLER { get; set; }
    public float PRICE1 { get; set; }
    public float PRICE2 { get; set; }
    public float PRICE3 { get; set; }
    public float PRICE4 { get; set; }
    public float PRICE5 { get; set; }
    public float PRICE6 { get; set; }
    public float PRICE7 { get; set; }
    public float PRICE8 { get; set; }
    public float PRICE9 { get; set; }
    public float DISCOUNT { get; set; }
    public float STANDARTCOST { get; set; }
    public float LASTCOST { get; set; }
    public float AVARAGECOST { get; set; }
    public float QTY { get; set; }
    public float MINIQTY { get; set; }
    public float MAXQTY { get; set; }
    public float ENTRYQTY { get; set; }
    public float SOLDQTY { get; set; }
    public float TRNQTY { get; set; }
    public float ORDQTY { get; set; }
    public float DIFQTY { get; set; }
    public DateTime ENTRYDATE { get; set; }
    public DateTime SOLDDATE { get; set; }
    public DateTime ORDDATE { get; set; }
    public DateTime DIFDATE { get; set; }
    public DateTime UPDDATE { get; set; }
    public int SUPPLIER { get; set; }
    public string IT_SALE { get; set; }
    public string IT_CHPRICE { get; set; }
    public string SCALE { get; set; }
    public string FATHER { get; set; }
    public string OTHERS { get; set; }
    public string COIN { get; set; }
    public short COLOR { get; set; }
    public short MIDA { get; set; }
    public short SMELL { get; set; }
    public string IT_DESC2 { get; set; }
    public float QTYPERUNIT { get; set; }
    public string NOVAT { get; set; }
    public string IF_DISCOUNT { get; set; }
    public float COSTPERC { get; set; }
    public string SALEREMARK { get; set; }
    public float PROFITPERC { get; set; }
    public string ICOM { get; set; }
}

public class RactTable
{
    public int CLNUM { get; set; }
    public string CLNAME { get; set; }
    public string ADDRESS { get; set; }
    public string FLOOR { get; set; }
    public string APPARTMENT { get; set; }
    public string ENTRY { get; set; }
    public string CITY { get; set; }
    public string ZIP { get; set; }
    public string HPHONE { get; set; }
    public string WPHONE { get; set; }
    public string FAX { get; set; }
    public int AGENT { get; set; }
    public int WRS { get; set; }
    public int CASHIER { get; set; }
    public int KIND { get; set; }
    public int CUT { get; set; }
    public int CLSORT { get; set; }
    public int STATUS { get; set; }
    public string CR_CARD { get; set; }
    public string TOKEF { get; set; }
    public string ID { get; set; }
    public string NOVAT { get; set; }
    public string PRICECODE { get; set; }
    public float DISCOUNT { get; set; }
    public float REMARK_PRINT { get; set; }
    public DateTime BIRTHDATE { get; set; }
    public DateTime START_DATE { get; set; }
    public DateTime LAST_UPDATE { get; set; }
    public DateTime TRAN_UPDATE { get; set; }
    public string TRAN_KIND { get; set; }
    public float DEBIT { get; set; }
    public float CREDIT { get; set; }
    public float BALLANCE { get; set; }
    public string STREET { get; set; }
    public string HOUSE { get; set; }
    public string EMAIL { get; set; }
    public string SPHONE { get; set; }
    public DateTime LAST { get; set; }
    public int REGISTRATIONAMT { get; set; }
    public DateTime CLUBRENEW { get; set; }
    public DateTime CLUBENDPERIOD { get; set; }
    public string STIKER { get; set; }
    public string CURRENCY { get; set; }
    public string CREDITDAYS { get; set; }
    public string EMAILMARK { get; set; }
    public string RACTPASWARD { get; set; }
    public float OBLIGO { get; set; }
    public float MAINACCOUNT { get; set; }
    public DateTime MARIGEDT { get; set; }
    public string IF_TRANSFER { get; set; }
    public string REDUCEVAT { get; set; }
    public string REMARK_DISPLAY { get; set; }
    public string IVC_TRAN { get; set; }
    public string WITHVAT { get; set; }
    public float POINTS { get; set; }
    public string ACCACCOUNT { get; set; }
    public short SUGINV { get; set; }
    public float DOCOBLIGO { get; set; }
    public string NOPRICE { get; set; }
}

public class MidaTable
{
    public short CODE { get; set; }
    public string DESC1 { get; set; }
    public string DESC2 { get; set; }
}

public class MeansTable
{
    public short MAINKEY { get; set; }
    public string DESCRIPTION { get; set; }
    public float AMMOUNT { get; set; }
}

public class Doc_HeadTable
{
    public System.Int32 NUMBER { get; set; }
    public DateTime ACCDATE { get; set; }
    public DateTime ACCTIME { get; set; }
    public int CL_NUM { get; set; }
    public string CL_NAME { get; set; }
    public string CL_ADDRESS { get; set; }
    public short SHIFTMANAGER { get; set; }
    public int CASHIER { get; set; }
    public short SALEPERSON { get; set; }
    public short PRICECODE { get; set; }
    public string CREDITDAYS { get; set; }
    public short ROUND { get; set; }
    public string STATUS { get; set; }
    public float TOTAL_B { get; set; }
    public float DISCT_T { get; set; }
    public float DISCT_P { get; set; }
    public float TOTAL_F { get; set; }
    public float HOV { get; set; }
    public float TOTAL_B_CUR { get; set; }
    public float DISCT_T_CUR { get; set; }
    public float TOTAL_F_CUR { get; set; }
    public float VAT { get; set; }
    public float VAT_PERC { get; set; }
    public string CL_PHONE { get; set; }
    public float BON { get; set; }
    public float SHIPPING { get; set; }
    public string CURRENCYSYMBOL { get; set; }
    public int Z_NUMBER { get; set; }
    public string ICOM { get; set; }
}

public class Doc_ItemTable
{
    public int NUMBER { get; set; }
    public int IT_LINE { get; set; }
    public string IT_CODE { get; set; }
    public string IT_DESC { get; set; }
    public float IT_QTY { get; set; }
    public float BONUS { get; set; }
    public float IT_PRICE { get; set; }
    public float IT_PRICE_CUR { get; set; }
    public float IT_DISC { get; set; }
    public float IT_TOTAL { get; set; }
    public float IT_TOTAL_CUR { get; set; }
    public int ORDNUMBER { get; set; }
    public short ORDLINE { get; set; }
    public short COLOR { get; set; }
    public short MIDA { get; set; }
    public short SALEPERSON { get; set; }
    public short CASHIER { get; set; }
    public string IT_CHPRICE { get; set; }
    public DateTime DLV_DATE { get; set; }
    public int CL_NUM { get; set; }
    public string SALE { get; set; }
    public string NOVAT { get; set; }
    public string BARDISCT { get; set; }
    public string SCALE { get; set; }
    public string ICOM { get; set; }
}

public class PaylistTable
{
    public int NUMBER { get; set; }
    public DateTime PDATE { get; set; }
    public DateTime PTIME { get; set; }
    public float CASH { get; set; }
    public float CHECKS { get; set; }
    public float CRDCARD { get; set; }
    public float CREDIT { get; set; }
    public int CASHIER { get; set; }
    public float VOUCHER { get; set; }
    public float HAKAFA { get; set; }
    public float FCURRENCY { get; set; }
    public float TOTAL_PAY { get; set; }
    public float PAYMENT { get; set; }
    public float CHANGE { get; set; }
    public float CR_VCHR { get; set; }
    public int Z_NUMBER { get; set; }
    public int PSELECT { get; set; }
    public short PAY_TO { get; set; }
    public string PSTATUS { get; set; }
    public string ICOM { get; set; }
    public float CASHDROWELL { get; set; }
    public float CASHFEE { get; set; }
    public float CELARIX { get; set; }
}

public class Sum_Doc
{
    public float SUM_IT_TOTAL { get; set; }
    public float SUM_VAT { get; set; }
    public float SUM_NOVAT { get; set; }
    public float SUM_BARDISCOUNT { get; set; }
    public float SUM_IT_QTY { get; set; }
    public float SUM_IT_TOTAL_CUR { get; set; }
}

public class ButtonsCTable
{
    public int LEVELKEY { get; set; }
    public int BUTTONNBR { get; set; }
    public string BUTTONDESC { get; set; }
    public short BUTTONTYPE { get; set; }
    public string BUTTONCOLOR { get; set; }
    public string IT_CODE { get; set; }
    public string  PIC { get; set; }
}
    public class ButtonsTable
{
    public short LEVELKEY { get; set; }
    public string B01DESC { get; set; }
    public short B01FONT { get; set; }
    public short B01TYPE { get; set; }
    public string B01CODE { get; set; }
    public string B02DESC { get; set; }
    public short B02FONT { get; set; }
    public short B02TYPE { get; set; }
    public string B02CODE { get; set; }
    public string B03DESC { get; set; }
    public short B03FONT { get; set; }
    public short B03TYPE { get; set; }
    public string B03CODE { get; set; }
    public string B04DESC { get; set; }
    public short B04FONT { get; set; }
    public short B04TYPE { get; set; }
    public string B04CODE { get; set; }
    public string B05DESC { get; set; }
    public short B05FONT { get; set; }
    public short B05TYPE { get; set; }
    public string B05CODE { get; set; }
    public string B06DESC { get; set; }
    public short B06FONT { get; set; }
    public short B06TYPE { get; set; }
    public string B06CODE { get; set; }
    public string B07DESC { get; set; }
    public short B07FONT { get; set; }
    public short B07TYPE { get; set; }
    public string B07CODE { get; set; }
    public string B08DESC { get; set; }
    public short B08FONT { get; set; }
    public short B08TYPE { get; set; }
    public string B08CODE { get; set; }
    public string B09DESC { get; set; }
    public short B09FONT { get; set; }
    public short B09TYPE { get; set; }
    public string B09CODE { get; set; }
    public string B010DESC { get; set; }
    public short B010FONT { get; set; }
    public short B010TYPE { get; set; }
    public string B010CODE { get; set; }
    public string B011DESC { get; set; }
    public short B011FONT { get; set; }
    public short B011TYPE { get; set; }
    public string B011CODE { get; set; }
    public string B012DESC { get; set; }
    public short B012FONT { get; set; }
    public short B012TYPE { get; set; }
    public string B012CODE { get; set; }
    public string B013DESC { get; set; }
    public short B013FONT { get; set; }
    public short B013TYPE { get; set; }
    public string B013CODE { get; set; }
    public string B014DESC { get; set; }
    public short B014FONT { get; set; }
    public short B014TYPE { get; set; }
    public string B014CODE { get; set; }
    public string B015DESC { get; set; }
    public short B015FONT { get; set; }
    public short B015TYPE { get; set; }
    public string B015CODE { get; set; }
    public string B016DESC { get; set; }
    public short B016FONT { get; set; }
    public short B016TYPE { get; set; }
    public string B016CODE { get; set; }
    public string B017DESC { get; set; }
    public short B017FONT { get; set; }
    public short B017TYPE { get; set; }
    public string B017CODE { get; set; }
    public string B018DESC { get; set; }
    public short B018FONT { get; set; }
    public short B018TYPE { get; set; }
    public string B018CODE { get; set; }
    public string B019DESC { get; set; }
    public short B019FONT { get; set; }
    public short B019TYPE { get; set; }
    public string B019CODE { get; set; }
    public string B020DESC { get; set; }
    public short B020FONT { get; set; }
    public short B020TYPE { get; set; }
    public string B020CODE { get; set; }
    public string B021DESC { get; set; }
    public short B021FONT { get; set; }
    public short B021TYPE { get; set; }
    public string B021CODE { get; set; }
    public string B022DESC { get; set; }
    public short B022FONT { get; set; }
    public short B022TYPE { get; set; }
    public string B022CODE { get; set; }
    public string B023DESC { get; set; }
    public short B023FONT { get; set; }
    public short B023TYPE { get; set; }
    public string B023CODE { get; set; }
    public string B024DESC { get; set; }
    public short B024FONT { get; set; }
    public short B024TYPE { get; set; }
    public string B024CODE { get; set; }
    public string B025DESC { get; set; }
    public short B025FONT { get; set; }
    public short B025TYPE { get; set; }
    public string B025CODE { get; set; }
    public string B026DESC { get; set; }
    public short B026FONT { get; set; }
    public short B026TYPE { get; set; }
    public string B026CODE { get; set; }
    public string B027DESC { get; set; }
    public short B027FONT { get; set; }
    public short B027TYPE { get; set; }
    public string B027CODE { get; set; }
    public string B028DESC { get; set; }
    public short B028FONT { get; set; }
    public short B028TYPE { get; set; }
    public string B028CODE { get; set; }
    public string B029DESC { get; set; }
    public short B029FONT { get; set; }
    public short B029TYPE { get; set; }
    public string B029CODE { get; set; }
    public string B030DESC { get; set; }
    public short B030FONT { get; set; }
    public short B030TYPE { get; set; }
    public string B030CODE { get; set; }
    public string B031DESC { get; set; }
    public short B031FONT { get; set; }
    public short B031TYPE { get; set; }
    public string B031CODE { get; set; }
    public string B032DESC { get; set; }
    public short B032FONT { get; set; }
    public short B032TYPE { get; set; }
    public string B032CODE { get; set; }
    public string B033DESC { get; set; }
    public short B033FONT { get; set; }
    public short B033TYPE { get; set; }
    public string B033CODE { get; set; }
    public string B034DESC { get; set; }
    public short B034FONT { get; set; }
    public short B034TYPE { get; set; }
    public string B034CODE { get; set; }
    public string B035DESC { get; set; }
    public short B035FONT { get; set; }
    public short B035TYPE { get; set; }
    public string B035CODE { get; set; }
    public string B036DESC { get; set; }
    public short B036FONT { get; set; }
    public short B036TYPE { get; set; }
    public string B036CODE { get; set; }
    public string B037DESC { get; set; }
    public short B037FONT { get; set; }
    public short B037TYPE { get; set; }
    public string B037CODE { get; set; }
    public string B038DESC { get; set; }
    public short B038FONT { get; set; }
    public short B038TYPE { get; set; }
    public string B038CODE { get; set; }
    public string B039DESC { get; set; }
    public short B039FONT { get; set; }
    public short B039TYPE { get; set; }
    public string B039CODE { get; set; }
    public string B040DESC { get; set; }
    public short B040FONT { get; set; }
    public short B040TYPE { get; set; }
    public string B040CODE { get; set; }
    public string B041DESC { get; set; }
    public short B041FONT { get; set; }
    public short B041TYPE { get; set; }
    public string B041CODE { get; set; }
    public string B042DESC { get; set; }
    public short B042FONT { get; set; }
    public short B042TYPE { get; set; }
    public string B042CODE { get; set; }
    public string B043DESC { get; set; }
    public short B043FONT { get; set; }
    public short B043TYPE { get; set; }
    public string B043CODE { get; set; }
    public string B044DESC { get; set; }
    public short B044FONT { get; set; }
    public short B044TYPE { get; set; }
    public string B044CODE { get; set; }
    public string B045DESC { get; set; }
    public short B045FONT { get; set; }
    public short B045TYPE { get; set; }
    public string B045CODE { get; set; }
    public string B046DESC { get; set; }
    public short B046FONT { get; set; }
    public short B046TYPE { get; set; }
    public string B046CODE { get; set; }
    public string B047DESC { get; set; }
    public short B047FONT { get; set; }
    public short B047TYPE { get; set; }
    public string B047CODE { get; set; }
    public string B048DESC { get; set; }
    public short B048FONT { get; set; }
    public short B048TYPE { get; set; }
    public string B048CODE { get; set; }
    public string B01COLOR { get; set; }
    public string B02COLOR { get; set; }
    public string B03COLOR { get; set; }
    public string B04COLOR { get; set; }
    public string B05COLOR { get; set; }
    public string B06COLOR { get; set; }
    public string B07COLOR { get; set; }
    public string B08COLOR { get; set; }
    public string B09COLOR { get; set; }
    public string B10COLOR { get; set; }
    public string B11COLOR { get; set; }
    public string B12COLOR { get; set; }
    public string B13COLOR { get; set; }
    public string B14COLOR { get; set; }
    public string B15COLOR { get; set; }
    public string B16COLOR { get; set; }
    public string B17COLOR { get; set; }
    public string B18COLOR { get; set; }
    public string B19COLOR { get; set; }
    public string B20COLOR { get; set; }
    public string B21COLOR { get; set; }
    public string B22COLOR { get; set; }
    public string B23COLOR { get; set; }
    public string B24COLOR { get; set; }
    public string B25COLOR { get; set; }
    public string B26COLOR { get; set; }
    public string B27COLOR { get; set; }
    public string B28COLOR { get; set; }
    public string B29COLOR { get; set; }
    public string B30COLOR { get; set; }
    public string B31COLOR { get; set; }
    public string B32COLOR { get; set; }
    public string B33COLOR { get; set; }
    public string B34COLOR { get; set; }
    public string B35COLOR { get; set; }
    public string B36COLOR { get; set; }
    public string B37COLOR { get; set; }
    public string B38COLOR { get; set; }
    public string B39COLOR { get; set; }
    public string B40COLOR { get; set; }
    public string B41COLOR { get; set; }
    public string B42COLOR { get; set; }
    public string B43COLOR { get; set; }
    public string B44COLOR { get; set; }
    public string B45COLOR { get; set; }
    public string B46COLOR { get; set; }
    public string B47COLOR { get; set; }
    public string B48COLOR { get; set; }
}
public class Buttons1
{
    public short LEVELKEY { get; set; }
    public string B01DESC { get; set; }
    public short B01FONT { get; set; }
    public short B01TYPE { get; set; }
    public string B01CODE { get; set; }
    public string B02DESC { get; set; }
    public short B02FONT { get; set; }
    public short B02TYPE { get; set; }
    public string B02CODE { get; set; }
    public string B03DESC { get; set; }
    public short B03FONT { get; set; }
    public short B03TYPE { get; set; }
    public string B03CODE { get; set; }
    public string B04DESC { get; set; }
    public short B04FONT { get; set; }
    public short B04TYPE { get; set; }
    public string B04CODE { get; set; }
    public string B05DESC { get; set; }
    public short B05FONT { get; set; }
    public short B05TYPE { get; set; }
    public string B05CODE { get; set; }
    public string B06DESC { get; set; }
    public short B06FONT { get; set; }
    public short B06TYPE { get; set; }
    public string B06CODE { get; set; }
    public string B07DESC { get; set; }
    public short B07FONT { get; set; }
    public short B07TYPE { get; set; }
    public string B07CODE { get; set; }
    public string B08DESC { get; set; }
    public short B08FONT { get; set; }
    public short B08TYPE { get; set; }
    public string B08CODE { get; set; }
    public string B09DESC { get; set; }
    public short B09FONT { get; set; }
    public short B09TYPE { get; set; }
    public string B09CODE { get; set; }
    public string B010DESC { get; set; }
    public short B010FONT { get; set; }
    public short B010TYPE { get; set; }
    public string B010CODE { get; set; }
    public string B011DESC { get; set; }
    public short B011FONT { get; set; }
    public short B011TYPE { get; set; }
    public string B011CODE { get; set; }
    public string B012DESC { get; set; }
    public short B012FONT { get; set; }
    public short B012TYPE { get; set; }
    public string B012CODE { get; set; }
    public string B013DESC { get; set; }
    public short B013FONT { get; set; }
    public short B013TYPE { get; set; }
    public string B013CODE { get; set; }
    public string B014DESC { get; set; }
    public short B014FONT { get; set; }
    public short B014TYPE { get; set; }
    public string B014CODE { get; set; }
    public string B015DESC { get; set; }
    public short B015FONT { get; set; }
    public short B015TYPE { get; set; }
    public string B015CODE { get; set; }
    public string B016DESC { get; set; }
    public short B016FONT { get; set; }
    public short B016TYPE { get; set; }
    public string B016CODE { get; set; }
    public string B017DESC { get; set; }
    public short B017FONT { get; set; }
    public short B017TYPE { get; set; }
    public string B017CODE { get; set; }
    public string B018DESC { get; set; }
    public short B018FONT { get; set; }
    public short B018TYPE { get; set; }
    public string B018CODE { get; set; }
    public string B019DESC { get; set; }
    public short B019FONT { get; set; }
    public short B019TYPE { get; set; }
    public string B019CODE { get; set; }
    public string B020DESC { get; set; }
    public short B020FONT { get; set; }
    public short B020TYPE { get; set; }
    public string B020CODE { get; set; }
    public string B021DESC { get; set; }
    public short B021FONT { get; set; }
    public short B021TYPE { get; set; }
    public string B021CODE { get; set; }
    public string B022DESC { get; set; }
    public short B022FONT { get; set; }
    public short B022TYPE { get; set; }
    public string B022CODE { get; set; }
    public string B023DESC { get; set; }
    public short B023FONT { get; set; }
    public short B023TYPE { get; set; }
    public string B023CODE { get; set; }
    public string B024DESC { get; set; }
    public short B024FONT { get; set; }
    public short B024TYPE { get; set; }
    public string B024CODE { get; set; }
    public string B025DESC { get; set; }
    public short B025FONT { get; set; }
    public short B025TYPE { get; set; }
    public string B025CODE { get; set; }
    public string B026DESC { get; set; }
    public short B026FONT { get; set; }
    public short B026TYPE { get; set; }
    public string B026CODE { get; set; }
    public string B027DESC { get; set; }
    public short B027FONT { get; set; }
    public short B027TYPE { get; set; }
    public string B027CODE { get; set; }
    public string B028DESC { get; set; }
    public short B028FONT { get; set; }
    public short B028TYPE { get; set; }
    public string B028CODE { get; set; }
    public string B029DESC { get; set; }
    public short B029FONT { get; set; }
    public short B029TYPE { get; set; }
    public string B029CODE { get; set; }
    public string B030DESC { get; set; }
    public short B030FONT { get; set; }
    public short B030TYPE { get; set; }
    public string B030CODE { get; set; }
    public string B031DESC { get; set; }
    public short B031FONT { get; set; }
    public short B031TYPE { get; set; }
    public string B031CODE { get; set; }
    public string B032DESC { get; set; }
    public short B032FONT { get; set; }
    public short B032TYPE { get; set; }
    public string B032CODE { get; set; }
    public string B033DESC { get; set; }
    public short B033FONT { get; set; }
    public short B033TYPE { get; set; }
    public string B033CODE { get; set; }
    public string B034DESC { get; set; }
    public short B034FONT { get; set; }
    public short B034TYPE { get; set; }
    public string B034CODE { get; set; }
    public string B035DESC { get; set; }
    public short B035FONT { get; set; }
    public short B035TYPE { get; set; }
    public string B035CODE { get; set; }
    public string B036DESC { get; set; }
    public short B036FONT { get; set; }
    public short B036TYPE { get; set; }
    public string B036CODE { get; set; }
    public string B037DESC { get; set; }
    public short B037FONT { get; set; }
    public short B037TYPE { get; set; }
    public string B037CODE { get; set; }
    public string B038DESC { get; set; }
    public short B038FONT { get; set; }
    public short B038TYPE { get; set; }
    public string B038CODE { get; set; }
    public string B039DESC { get; set; }
    public short B039FONT { get; set; }
    public short B039TYPE { get; set; }
    public string B039CODE { get; set; }
    public string B040DESC { get; set; }
    public short B040FONT { get; set; }
    public short B040TYPE { get; set; }
    public string B040CODE { get; set; }
    public string B041DESC { get; set; }
    public short B041FONT { get; set; }
    public short B041TYPE { get; set; }
    public string B041CODE { get; set; }
    public string B042DESC { get; set; }
    public short B042FONT { get; set; }
    public short B042TYPE { get; set; }
    public string B042CODE { get; set; }
    public string B043DESC { get; set; }
    public short B043FONT { get; set; }
    public short B043TYPE { get; set; }
    public string B043CODE { get; set; }
    public string B044DESC { get; set; }
    public short B044FONT { get; set; }
    public short B044TYPE { get; set; }
    public string B044CODE { get; set; }
    public string B045DESC { get; set; }
    public short B045FONT { get; set; }
    public short B045TYPE { get; set; }
    public string B045CODE { get; set; }
    public string B046DESC { get; set; }
    public short B046FONT { get; set; }
    public short B046TYPE { get; set; }
    public string B046CODE { get; set; }
    public string B047DESC { get; set; }
    public short B047FONT { get; set; }
    public short B047TYPE { get; set; }
    public string B047CODE { get; set; }
    public string B048DESC { get; set; }
    public short B048FONT { get; set; }
    public short B048TYPE { get; set; }
    public string B048CODE { get; set; }
    public string B01COLOR { get; set; }
    public string B02COLOR { get; set; }
    public string B03COLOR { get; set; }
    public string B04COLOR { get; set; }
    public string B05COLOR { get; set; }
    public string B06COLOR { get; set; }
    public string B07COLOR { get; set; }
    public string B08COLOR { get; set; }
    public string B09COLOR { get; set; }
    public string B10COLOR { get; set; }
    public string B11COLOR { get; set; }
    public string B12COLOR { get; set; }
    public string B13COLOR { get; set; }
    public string B14COLOR { get; set; }
    public string B15COLOR { get; set; }
    public string B16COLOR { get; set; }
    public string B17COLOR { get; set; }
    public string B18COLOR { get; set; }
    public string B19COLOR { get; set; }
    public string B20COLOR { get; set; }
    public string B21COLOR { get; set; }
    public string B22COLOR { get; set; }
    public string B23COLOR { get; set; }
    public string B24COLOR { get; set; }
    public string B25COLOR { get; set; }
    public string B26COLOR { get; set; }
    public string B27COLOR { get; set; }
    public string B28COLOR { get; set; }
    public string B29COLOR { get; set; }
    public string B30COLOR { get; set; }
    public string B31COLOR { get; set; }
    public string B32COLOR { get; set; }
    public string B33COLOR { get; set; }
    public string B34COLOR { get; set; }
    public string B35COLOR { get; set; }
    public string B36COLOR { get; set; }
    public string B37COLOR { get; set; }
    public string B38COLOR { get; set; }
    public string B39COLOR { get; set; }
    public string B40COLOR { get; set; }
    public string B41COLOR { get; set; }
    public string B42COLOR { get; set; }
    public string B43COLOR { get; set; }
    public string B44COLOR { get; set; }
    public string B45COLOR { get; set; }
    public string B46COLOR { get; set; }
    public string B47COLOR { get; set; }
    public string B48COLOR { get; set; }
}


